<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/amazon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv',encoding='ISO-8859-1')
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
new={'ano':'year','mes':'month','estado':'state','numero':'no_of_fires','encontro':'date'}
df.rename(columns=new,inplace='True')
df

      year     month      state no_of_fires      date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df['month'].unique()

array(['Janeiro', 'Fevereiro', 'MarÃ§o', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [ ]:
new={'Janeiro':'january', 'Fevereiro':'february', 'MarÃ§o':'march', 'Abril':'april', 'Maio':'may', 'Junho':'june', 'Julho':'july',
       'Agosto':'august', 'Setembro':'september', 'Outubro':'october', 'Novembro':'november', 'Dezembro':'december'}
df['month']=df['month'].map(new)
df

      year     month      state no_of_fires      date
0     1998   january       Acre     0 Fires  1/1/1998
1     1999   january       Acre     0 Fires  1/1/1999
2     2000   january       Acre     0 Fires  1/1/2000
3     2001   january       Acre     0 Fires  1/1/2001
4     2002   january       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  december  Tocantins         128  1/1/2012
6450  2013  december  Tocantins          85  1/1/2013
6451  2014  december  Tocantins         223  1/1/2014
6452  2015  december  Tocantins         373  1/1/2015
6453  2016  december  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df['no_of_fires']=df['no_of_fires'].str.strip(' Fires')
df

      year     month      state no_of_fires      date
0     1998   january       Acre           0  1/1/1998
1     1999   january       Acre           0  1/1/1999
2     2000   january       Acre           0  1/1/2000
3     2001   january       Acre           0  1/1/2001
4     2002   january       Acre           0  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  december  Tocantins         128  1/1/2012
6450  2013  december  Tocantins          85  1/1/2013
6451  2014  december  Tocantins         223  1/1/2014
6452  2015  december  Tocantins         373  1/1/2015
6453  2016  december  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df['no_of_fires']=df['no_of_fires'].astype(float)

In [ ]:
# avg=df['no_of_fires'].mean()
df['no_of_fires']=df['no_of_fires'].fillna(0)

In [ ]:
df['no_of_fires']=df['no_of_fires'].astype(int)

#1) Total number of fires in the month of January

In [ ]:
var=df.groupby(['month'])
jan=var.get_group('january')['no_of_fires'].sum()
jan

<ipython-input-111-d06f2370ff6a>:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  jan=var.get_group('january')['no_of_fires'].sum()

47042

In [ ]:
df

      year     month      state  no_of_fires      date
0     1998   january       Acre            0  1/1/1998
1     1999   january       Acre            0  1/1/1999
2     2000   january       Acre            0  1/1/2000
3     2001   january       Acre            0  1/1/2001
4     2002   january       Acre            0  1/1/2002
...    ...       ...        ...          ...       ...
6449  2012  december  Tocantins          128  1/1/2012
6450  2013  december  Tocantins           85  1/1/2013
6451  2014  december  Tocantins          223  1/1/2014
6452  2015  december  Tocantins          373  1/1/2015
6453  2016  december  Tocantins          119  1/1/2016

[6454 rows x 5 columns]

#2) Total number of fires in 2002.

In [ ]:
# df['date'].value_counts()

In [ ]:
var=df[df['date']=='1/1/2002']
sum_no_of_fires=var['no_of_fires'].sum()
sum_no_of_fires

37820

#3) Total number of fires in year 2001

In [ ]:
var1=df[df['date']=='1/1/2001']
sum_no_of_fires1=var1['no_of_fires'].sum()
sum_no_of_fires1

28823

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv')
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

#4) how many ppl survived in b5 cabin

In [ ]:
df['survived'].value_counts()

survived
0    809
1    500
Name: count, dtype: int64

In [ ]:
survived=df[(df['survived']==1) & (df['cabin']=='B5')]['survived'].count()
survived

2

In [ ]:
var2=df.groupby(['survived','cabin'])
data=var2.get_group((1,'B5'))['survived'].count()
data

2

# 5) count of females whose age is less than 20 and survived

In [ ]:
age=df[(df['age']<20) &(df['survived']==1) & (df['sex']=='female')]['survived'].count()
age

72

#6) Total fare paid by embarked S females

In [ ]:
females=df.groupby(['embarked','sex'])
fare=females.get_group(('S','female'))['fare'].sum()
fare

11447.7378

In [ ]:
fare1=df[(df['embarked']=="S") & (df['sex']=='female')]['fare'].sum()
fare1

11447.7378

#7) count of ppl in pclass 3 having only 1 person with them

In [ ]:
count=df[(df['pclass']==3) & (df['sibsp']==1)]['pclass'].count()
count

124

In [ ]:
ppl=df.groupby(['pclass','sibsp'])
count_ppl=ppl.get_group((3,1))['pclass'].count()
count_ppl

124

#8) maximum fare paid in embarked Q

In [ ]:
max=df[(df['embarked']=='Q')]['fare'].max()
max

90.0

In [ ]:
max_fare=df.groupby('embarked')
max_Q=max_fare.get_group('Q')['fare'].max()
max_Q

90.0

#9) Avg time spend by the ppl in support department who got promoted

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/hr_data.csv')
df.head(3)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium

In [ ]:
time_spend=df.groupby(['department','promotion_last_5years'])
avg_time=time_spend.get_group(('support',1))['time_spend_company'].mean()
avg_time

3.45

In [ ]:
time=df[(df['department']=='support') & (df['promotion_last_5years']==1)]['time_spend_company'].mean()
time

3.45

#10) avg number of projects ppl with high salary are handling in IT department

In [ ]:
df.head(2)
avg_n=df.groupby(['salary','department'])
avg_projects=avg_n.get_group(('high','IT'))['number_project'].mean()
avg_projects

3.8674698795180724

In [ ]:
avg_no=df[(df['salary']=='high') & (df['department']=='IT')]['number_project'].mean()
avg_no

3.8674698795180724

#11) Total number of projects handled by support department.

In [ ]:
total=df[df['department']=='support']['number_project'].sum()
total

8479

#12) Count of people in sales department who have work accident

In [ ]:
count_sales=df.groupby(['department','Work_accident'])
count_ppl=count_sales.get_group(('sales',1))['employee_id'].count()
count_ppl

587

In [ ]:
count_s=df[(df['department']=='sales') & (df['Work_accident']==1)]['employee_id'].count()
count_s

587