<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/Data_cleaning_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/employee_data.csv')

In [ ]:
df

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28.0,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33.0,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent

#Rename Columns:
#The column names are not standardized.
##Rename the following columns:
###▪ full_name to name
###▪ emp_id to employee_id
###▪ emp_status to employment_status

In [ ]:
d={'full_name':'name','emp_id':'employee_id','emp_status':'employment_status'}
df.rename(columns=d,inplace=True)
df

,employee_id,name,age,gender,department,salary,join_date,exp_years,employment_status
0,101,John A. Smith,28.0,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33.0,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent

#2. Rearrange Columns:

##Rearrange the columns in this order:
 ▪ employee_id, name, age, gender, department,join_date,
exp_years,salary,employment_status

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        16 non-null     int64
 1   name               16 non-null     object
 2   age                12 non-null     float64
 3   gender             15 non-null     object
 4   department         16 non-null     object
 5   salary             15 non-null     float64
 6   join_date          15 non-null     object
 7   exp_years          11 non-null     float64
 8   employment_status  15 non-null     object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.2+ KB

In [ ]:
items=[0,1,2,3,4,6,7,5,8]
df=df[df.columns[items]]
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28.0,male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,Male,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent

#3. Update Column Values (Mapping):

##In the gender column, map the values as follows:
▪ male and Male should be updated to M

▪ female and Female should be updated to F

In [ ]:
df.columns

Index(['employee_id', 'name', 'age', 'gender', 'department', 'join_date',
       'exp_years', 'salary', 'employment_status'],
      dtype='object')

In [ ]:
d={'male':'M','Male':'M',"female":'F','Female':'F'}
df['gender']=df['gender'].map(d)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28.0,M,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,M,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,F,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,M,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,F,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,M,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,F,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent

#4. Remove Unwanted Characters:

##Remove any leading or trailing spaces in the name column.

In [ ]:
df['name']=df['name'].str.strip()
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28.0,M,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,M,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,F,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,M,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,F,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,M,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,F,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,M,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,F,Marketing,2018-11-03,NaN,50000.0,permanent

#5. Change Data Type:

##Convert the age column to integer type, and the salary column to int type.

In [ ]:
# df['age']=df['age'].fillna(0)
df['age']=df['age'].astype(int)
df['salary']=df['salary'].astype(int)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,5.0,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
2,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
3,103,Mark O'Donnell,35,M,HR,2016-03-11,8.0,52000,NaN
4,104,Emily Jackson-Smith,29,F,R&D,2016-03-11,6.0,65000,contract
5,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
6,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
7,105,Samuel L. Jackson,42,M,IT,2015-07-01,12.0,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000,contract
9,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
10,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
11,107,Susan M. Thompson,39,F,IT,2014-09-21,NaN,75000,permanent
12,108,Brian P. McDonald,33,M,HR,2017-04-15,6.0,48000,permanent
13,109,Sophia Y. Richardson,26,F,IT,2020-05-30,3.0,55000,contract
14,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
15,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent

#6. Replace Specific Values:

##In the employment_status column, replace missing values with 'contract'.

In [ ]:
df['employment_status']=df['employment_status'].fillna('contract')
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,5.0,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
2,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
3,103,Mark O'Donnell,35,M,HR,2016-03-11,8.0,52000,contract
4,104,Emily Jackson-Smith,29,F,R&D,2016-03-11,6.0,65000,contract
5,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
6,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
7,105,Samuel L. Jackson,42,M,IT,2015-07-01,12.0,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000,contract
9,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
10,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
11,107,Susan M. Thompson,39,F,IT,2014-09-21,NaN,75000,permanent
12,108,Brian P. McDonald,33,M,HR,2017-04-15,6.0,48000,permanent
13,109,Sophia Y. Richardson,26,F,IT,2020-05-30,3.0,55000,contract
14,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
15,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent

#7. Handle Missing Values:

##o Fill missing values in the age column with the average age of the employees.
##o Fill missing values in the salary column with the median salary.
##o For missing join_date, use forward fill (ffill).

In [ ]:

avg=df['age'].mean()
avg1=df['salary'].median()

df['age']=df['age'].fillna(avg)
df['salary']=df['salary'].fillna(avg1)
df['join_date']=df['join_date'].fillna(method='ffill')


df

<ipython-input-51-1108ccc9c676>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['join_date']=df['join_date'].fillna(method='ffill')

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28.000000,M,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36.916667,F,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.000000,M,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.000000,M,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.000000,F,R&D,2016-03-11,6.0,65000.0,contract
5,102,Sarah-Louise James,36.916667,F,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.000000,M,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.000000,M,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31.000000,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36.916667,F,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.000000,M,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.000000,F,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.000000,M,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.000000,F,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.000000,M,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36.916667,F,Marketing,2018-11-03,NaN,50000.0,permanent

#8. Remove Duplicates:
o Ensure there are no duplicate rows in the dataset.

In [ ]:
df.drop_duplicates(inplace=True)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,5.0,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
2,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
3,103,Mark O'Donnell,35,M,HR,2016-03-11,8.0,52000,contract
4,104,Emily Jackson-Smith,29,F,R&D,2016-03-11,6.0,65000,contract
7,105,Samuel L. Jackson,42,M,IT,2015-07-01,12.0,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000,contract
11,107,Susan M. Thompson,39,F,IT,2014-09-21,NaN,75000,permanent
12,108,Brian P. McDonald,33,M,HR,2017-04-15,6.0,48000,permanent
13,109,Sophia Y. Richardson,26,F,IT,2020-05-30,3.0,55000,contract

#9. Apply String Function:
o Capitalize the first letter of each word in the department column.

In [ ]:
df['department']=df['department'].str.capitalize()
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,5.0,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,NaN,50000,permanent
2,110,Rajesh Kumar,45,M,Sales,2010-02-23,14.0,90000,permanent
3,103,Mark O'Donnell,35,M,Hr,2016-03-11,8.0,52000,contract
4,104,Emily Jackson-Smith,29,F,R&d,2016-03-11,6.0,65000,contract
7,105,Samuel L. Jackson,42,M,It,2015-07-01,12.0,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000,contract
11,107,Susan M. Thompson,39,F,It,2014-09-21,NaN,75000,permanent
12,108,Brian P. McDonald,33,M,Hr,2017-04-15,6.0,48000,permanent
13,109,Sophia Y. Richardson,26,F,It,2020-05-30,3.0,55000,contract

#10. Drop Unwanted Columns:
o Remove the exp_years column from the dataset.

In [ ]:
df.drop('exp_years',axis=1,inplace=True)
df

,employee_id,name,age,gender,department,join_date,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,50000,permanent
2,110,Rajesh Kumar,45,M,Sales,2010-02-23,90000,permanent
3,103,Mark O'Donnell,35,M,Hr,2016-03-11,52000,contract
4,104,Emily Jackson-Smith,29,F,R&d,2016-03-11,65000,contract
7,105,Samuel L. Jackson,42,M,It,2015-07-01,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000,contract
11,107,Susan M. Thompson,39,F,It,2014-09-21,75000,permanent
12,108,Brian P. McDonald,33,M,Hr,2017-04-15,48000,permanent
13,109,Sophia Y. Richardson,26,F,It,2020-05-30,55000,contract

#11. Remove Specific Rows:
o Drop rows where salary is above 80,000 to focus on mid-level employees.

In [ ]:
var=df[df['salary']> 80000]
var
df.drop(df.index[2],inplace=True)
df

,employee_id,name,age,gender,department,join_date,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,50000,permanent
4,104,Emily Jackson-Smith,29,F,R&d,2016-03-11,65000,contract
7,105,Samuel L. Jackson,42,M,It,2015-07-01,55000,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000,contract
11,107,Susan M. Thompson,39,F,It,2014-09-21,75000,permanent
12,108,Brian P. McDonald,33,M,Hr,2017-04-15,48000,permanent
13,109,Sophia Y. Richardson,26,F,It,2020-05-30,55000,contract

#12. Reset Index:
o After cleaning, reset the index of the DataFrame.

In [ ]:
df.drop('index',axis=1,inplace=True)
df.reset_index(inplace=True)
df

,employee_id,name,age,gender,department,join_date,salary,employment_status
0,101,John A. Smith,28,M,Sales,2017-08-19,45000,permanent
1,102,Sarah-Louise James,36,F,Marketing,2018-11-03,50000,permanent
2,104,Emily Jackson-Smith,29,F,R&d,2016-03-11,65000,contract
3,105,Samuel L. Jackson,42,M,It,2015-07-01,55000,permanent
4,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000,contract
5,107,Susan M. Thompson,39,F,It,2014-09-21,75000,permanent
6,108,Brian P. McDonald,33,M,Hr,2017-04-15,48000,permanent
7,109,Sophia Y. Richardson,26,F,It,2020-05-30,55000,contract

#13. Set Column as Index:
o Set the employee_id as the index of the DataFrame.

In [ ]:
df.set_index('employee_id',inplace=True)
df

,name,age,gender,department,join_date,salary,employment_status
employee_id,,,,,,,
101,John A. Smith,28,M,Sales,2017-08-19,45000,permanent
102,Sarah-Louise James,36,F,Marketing,2018-11-03,50000,permanent
104,Emily Jackson-Smith,29,F,R&d,2016-03-11,65000,contract
105,Samuel L. Jackson,42,M,It,2015-07-01,55000,permanent
106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000,contract
107,Susan M. Thompson,39,F,It,2014-09-21,75000,permanent
108,Brian P. McDonald,33,M,Hr,2017-04-15,48000,permanent
109,Sophia Y. Richardson,26,F,It,2020-05-30,55000,contract