<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/Groupby_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/hr_data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  object
 8   salary                 14999 non-null  object
dtypes: int64(7), object(2)
memory usage: 1.0+ MB

In [4]:
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [5]:
var=df.groupby('department')

In [6]:
var.groups

{'IT': [61, 62, 63, 64, 65, 70, 138, 139, 140, 141, 142, 147, 214, 215, 216, 217, 218, 223, 291, 292, 293, 294, 295, 300, 367, 368, 369, 370, 371, 376, 443, 444, 445, 446, 447, 452, 519, 520, 521, 522, 523, 528, 595, 596, 597, 598, 599, 604, 671, 672, 673, 674, 675, 680, 747, 748, 749, 750, 751, 756, 823, 824, 825, 826, 827, 832, 899, 900, 901, 902, 903, 908, 975, 976, 977, 978, 979, 984, 1051, 1052, 1053, 1054, 1055, 1060, 1127, 1128, 1129, 1130, 1131, 1136, 1204, 1205, 1206, 1207, 1208, 1213, 1214, 1215, 1216, 1281, ...], 'RandD': [301, 302, 303, 304, 305, 453, 454, 455, 456, 457, 605, 606, 607, 608, 609, 833, 834, 835, 836, 837, 985, 986, 987, 988, 989, 1061, 1062, 1063, 1064, 1065, 1217, 1218, 1219, 1291, 1292, 1293, 1294, 1295, 1296, 1368, 1369, 1370, 1371, 1372, 1373, 1445, 1446, 1447, 1448, 1449, 1450, 1522, 1523, 1524, 1525, 1526, 1598, 1599, 1600, 1601, 1602, 1675, 1676, 1677, 1678, 1679, 1751, 1752, 1753, 1754, 1755, 1827, 1828, 1829, 1830, 1831, 1903, 1904, 1905, 1906, 1907, 1979, 1980, 1981, 1982, 1983, 2055, 2056, 2057, 2058, 2059, 2131, 2132, 2133, 2134, 2135, 2207, 2208, 2209, 2210, ...], 'accounting': [28, 29, 30, 79, 105, 106, 107, 155, 181, 182, 183, 224, 225, 232, 258, 259, 260, 308, 334, 335, 336, 377, 378, 384, 410, 411, 412, 460, 486, 487, 488, 529, 530, 536, 562, 563, 564, 612, 638, 639, 640, 688, 714, 715, 716, 764, 790, 791, 792, 840, 866, 867, 868, 916, 942, 943, 944, 992, 1018, 1019, 1020, 1068, 1094, 1095, 1096, 1145, 1171, 1172, 1173, 1222, 1248, 1249, 1250, 1299, 1325, 1326, 1327, 1376, 1402, 1403, 1404, 1453, 1479, 1480, 1481, 1529, 1555, 1556, 1557, 1606, 1632, 1633, 1634, 1682, 1708, 1709, 1710, 1758, 1784, 1785, ...], 'hr': [31, 32, 33, 34, 108, 109, 110, 111, 184, 185, 186, 187, 226, 227, 228, 261, 262, 263, 264, 337, 338, 339, 340, 379, 380, 381, 413, 414, 415, 416, 489, 490, 491, 492, 531, 532, 533, 565, 566, 567, 568, 641, 642, 643, 644, 717, 718, 719, 720, 793, 794, 795, 796, 869, 870, 871, 872, 945, 946, 947, 948, 1021, 1022, 1023, 1024, 1097, 1098, 1099, 1100, 1174, 1175, 1176, 1177, 1251, 1252, 1253, 1254, 1328, 1329, 1330, 1331, 1405, 1406, 1407, 1408, 1482, 1483, 1484, 1485, 1558, 1559, 1560, 1561, 1635, 1636, 1637, 1638, 1711, 1712, 1713, ...], 'management': [60, 82, 137, 158, 213, 235, 290, 311, 366, 387, 442, 463, 518, 539, 594, 615, 670, 691, 746, 767, 822, 843, 898, 919, 974, 995, 1050, 1071, 1126, 1148, 1203, 1225, 1280, 1302, 1357, 1379, 1434, 1456, 1511, 1532, 1587, 1609, 1664, 1685, 1740, 1761, 1816, 1837, 1892, 1913, 1968, 1989, 2044, 2065, 2120, 2141, 2196, 2217, 2272, 2293, 2348, 2369, 2424, 2445, 2500, 2522, 2577, 2599, 2654, 2676, 2731, 2753, 2808, 2830, 2885, 2906, 2961, 2983, 3038, 3059, 3114, 3135, 3190, 3211, 3266, 3287, 3342, 3363, 3418, 3439, 3494, 3515, 3570, 3591, 3646, 3667, 3722, 3743, 3798, 3819, ...], 'marketing': [77, 83, 84, 85, 148, 149, 150, 151, 152, 153, 159, 160, 161, 229, 230, 236, 237, 238, 306, 312, 313, 314, 382, 388, 389, 390, 458, 464, 465, 466, 534, 540, 541, 542, 610, 616, 617, 618, 686, 692, 693, 694, 762, 768, 769, 770, 838, 844, 845, 846, 914, 920, 921, 922, 990, 996, 997, 998, 1066, 1072, 1073, 1074, 1142, 1143, 1149, 1150, 1151, 1220, 1226, 1227, 1228, 1297, 1303, 1304, 1305, 1374, 1380, 1381, 1382, 1451, 1457, 1458, 1459, 1527, 1533, 1534, 1535, 1603, 1604, 1610, 1611, 1612, 1680, 1686, 1687, 1688, 1756, 1762, 1763, 1764, ...], 'product_mng': [66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 143, 144, 145, 146, 219, 220, 221, 222, 296, 297, 298, 299, 372, 373, 374, 375, 448, 449, 450, 451, 524, 525, 526, 527, 600, 601, 602, 603, 676, 677, 678, 679, 752, 753, 754, 755, 828, 829, 830, 831, 904, 905, 906, 907, 980, 981, 982, 983, 1056, 1057, 1058, 1059, 1132, 1133, 1134, 1135, 1209, 1210, 1211, 1212, 1286, 1287, 1288, 1289, 1363, 1364, 1365, 1366, 1440, 1441, 1442, 1443, 1517, 1518, 1519, 1520, 1593, 1594, 1595, 1596, 1670, 1671, 1672, 1673, 1746, 1747, 1748, 1749, 1822, 1823, ...], 'sales': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 78, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 154, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 231, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 307, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, ...], 'support': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 80, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 156, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 233, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 309, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 385, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 461, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 537, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 613, 656, 657, 658, 659, ...], 'technical': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 57, 58, 59, 81, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 134, 135, 136, 157, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 210, 211, 212, 234, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 287, 288, 289, 310, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 363, 364, 365, 386, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 439, 440, 441, 462, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, ...]}

In [7]:
sales=var.get_group('sales')
sales

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14967,87507,2,128,3,0,1,0,sales,low
14968,87518,2,128,3,0,1,0,sales,medium
14969,87520,2,157,3,0,1,0,sales,medium
14970,87530,4,225,5,0,1,0,sales,medium
14971,87533,2,140,3,0,1,0,sales,medium

In [8]:
IT=var.get_group('IT')
IT

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [9]:
hr=var.get_group('hr')
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
31,1223,2,134,3,0,1,0,hr,low
32,1228,2,145,3,0,1,0,hr,low
33,1230,2,140,3,0,1,0,hr,low
34,1236,4,246,6,0,1,0,hr,low
108,1679,3,177,4,0,1,0,hr,medium
...,...,...,...,...,...,...,...,...,...
14902,87131,2,159,3,0,1,0,hr,high
14975,87560,7,310,4,0,1,0,hr,medium
14976,87562,2,136,3,0,1,0,hr,medium
14977,87579,4,251,6,0,1,0,hr,medium
14978,17938,2,144,3,0,1,0,hr,medium

In [10]:
accounting=var.get_group('accounting')
accounting

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
28,1203,2,128,3,0,1,0,accounting,low
29,1204,2,132,3,0,1,0,accounting,low
30,1214,6,294,4,0,1,0,accounting,low
79,1489,2,142,3,0,1,0,accounting,low
105,1669,7,224,5,0,1,0,accounting,medium
...,...,...,...,...,...,...,...,...,...
14898,87115,7,269,4,0,1,0,accounting,medium
14946,87365,5,303,5,0,1,0,accounting,medium
14972,87539,6,310,4,0,1,0,accounting,medium
14973,7745,2,143,3,0,1,0,accounting,medium
14974,87545,2,153,3,0,1,0,accounting,medium

In [11]:
RandD=var.get_group('RandD')
RandD

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
301,2847,3,278,4,0,1,0,RandD,medium
302,57006,7,250,5,0,1,0,RandD,medium
303,2880,2,127,3,0,1,0,RandD,medium
304,2881,5,255,5,0,1,0,RandD,medium
305,2882,2,135,3,0,1,0,RandD,medium
...,...,...,...,...,...,...,...,...,...
14939,87333,4,273,5,0,1,0,RandD,medium
14940,87335,5,285,4,1,1,0,RandD,medium
14941,87339,2,131,3,0,1,0,RandD,high
14942,87341,5,135,6,0,1,0,RandD,low
14943,96411,5,239,5,0,1,0,RandD,medium

In [12]:
support=var.get_group('support')
support

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
46,1310,2,147,3,0,1,0,support,low
47,1311,3,273,6,0,1,0,support,low
48,1316,2,148,3,0,1,0,support,low
49,1319,2,147,3,0,1,0,support,low
50,10865,6,152,2,0,1,0,support,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [13]:
var2=df.groupby('salary')
sal=var2.get_group('low')
sal

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

#we can use morethan one column as a categorial column in groupy class

In [14]:
var3=df.groupby(['department','salary'])
ds=var3.get_group(('IT','medium'))
ds

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [15]:
df.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='object')

In [16]:
var1=df.groupby(['department','left'])
var2=var1.get_group(('sales',1))['employee_id'].count()
print(var2)

1014

In [17]:
var2=var1.get_group(('IT',1))['employee_id'].count()
print(var2)

273

In [18]:
var3=df.groupby(['department'])
var4=var3.get_group(('support'))['number_project'].sum()
var4

<ipython-input-18-20f3f0d0a977>:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  var4=var3.get_group(('support'))['number_project'].sum()

8479

In [19]:
df.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='object')

In [20]:
var5=df.groupby(['promotion_last_5years','department'])
var6=var5.get_group((1,'accounting'))['employee_id'].count()
var6

14

In [21]:
r_d=var5.get_group((1,'RandD'))['employee_id'].count()
var6+r_d

41

In [22]:
var7=df.groupby(['salary','department'])
low=var7.get_group(('low','marketing'))['employee_id'].count()
high=var7.get_group(('high','marketing'))['employee_id'].count()
low+high

482

In [23]:
emp_sal=var7.get_group(('high','management'))['employee_id'].count()
emp_sal

225

In [24]:
product_mng=var3.get_group('product_mng')['number_project'].sum()
product_mng

<ipython-input-24-163e41538d0e>:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  product_mng=var3.get_group('product_mng')['number_project'].sum()

3434

In [25]:
df.tail(20)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
14979,87581,6,296,4,0,1,0,technical,medium
14980,20751,5,238,5,0,1,0,technical,high
14981,87597,5,162,4,0,1,0,technical,low
14982,87608,2,137,3,0,1,0,technical,medium
14983,87610,5,257,5,0,1,0,technical,medium
14984,87612,2,148,3,0,1,0,technical,medium
14985,87624,5,254,5,0,1,0,technical,medium
14986,87625,4,247,6,0,1,0,technical,low
14987,87632,5,206,4,0,1,0,technical,low
14988,87636,2,145,3,0,1,0,technical,low
14989,87638,2,159,3,1,1,0,technical,low
14990,87639,5,228,5,1,1,0,support,low
14991,87654,6,257,4,0,1,0,support,low
14992,87656,2,155,3,0,1,0,support,low
14993,87661,6,293,6,0,1,0,support,low
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [26]:
df['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)