<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
l=[10,3.6,78,90,3+4j,'hi']
l={'a':200,'b':300}
pd.Series(l,name='Data')

a    200
b    300
Name: Data, dtype: int64

In [ ]:
arr=np.arange(1,11)
pd.Series(arr,name='Num',index=['a','b','c','d','e','f','g','h','i','j'])

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
Name: Num, dtype: int64

In [ ]:
#create a series of uppercase alphabets 'A' to 'Z'

out=[]
for i in range(97,123):
  out.append(chr(i))

pd.Series(out,name='Alpha')

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: Alpha, dtype: object

In [ ]:
def is_prime(n):
  for i in range(2,n):
    if n%i==0:
      return False
  else:
    return True

out=[]
for i in range(2,101):
  if is_prime(i):
    out.append(i)
prime=pd.Series(out,name='Prime')
prime

0      2
1      3
2      5
3      7
4     11
5     13
6     17
7     19
8     23
9     29
10    31
11    37
12    41
13    43
14    47
15    53
16    59
17    61
18    67
19    71
20    73
21    79
22    83
23    89
24    97
Name: Prime, dtype: int64

In [ ]:
prime[0]
prime[7]
prime[24]
prime[4]

prime[1::]
prime[1:11]
prime[1:21:2]

prime[::2]


prime[1]=3000
prime

prime[24]=5000
prime

0        2
1     3000
2        5
3        7
4       11
5       13
6       17
7       19
8       23
9       29
10      31
11      37
12      41
13      43
14      47
15      53
16      59
17      61
18      67
19      71
20      73
21      79
22      83
23      89
24    5000
Name: Prime, dtype: int64

In [ ]:
p=prime[1::2]
pd.Series(p,name='prime2')

1     3000
3        7
5       13
7       19
9       29
11      37
13      43
15      53
17      61
19      71
21      79
23      89
Name: prime2, dtype: int64

In [ ]:
prime

p[1:6]=10,20,30,40,50

p

1     3000
3       10
5       20
7       30
9       40
11      50
13      43
15      53
17      61
19      71
21      79
23      89
Name: Prime, dtype: int64

In [ ]:
s=pd.Series([1,9,8,7,0])

# print(s)
s1=s.sort_values()


s1.reset_index()

   index  0
0      4  0
1      0  1
2      3  7
3      2  8
4      1  9

In [ ]:
123412141

123412141

In [ ]:
d={'Name':['Bob','John','Smith','Alex','Mark','Raj'],
   'roll':[1,2,3,4,5,6],
   'Marks':[56,90,87,79,49,100]}


df=pd.DataFrame(d)
df

    Name  roll  Marks
0    Bob     1     56
1   John     2     90
2  Smith     3     87
3   Alex     4     79
4   Mark     5     49
5    Raj     6    100

In [ ]:
#Create a dataframe with emp data Ename, eid, sal, deptno, dname

In [ ]:
df1=pd.DataFrame({'Ename':['A','B','C','D','E'],
                  'Eid':np.arange(1,6),
                  'sal':[25000,30000,50000,15000,5000],
                  'deptno':pd.Series([10,20,30,40,50]),
                  'Dname':['Dev','sales','accounts','HR','Testing']})
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  25000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
#Accessing

# syntax
# df['column_name']


df1['Ename']
df1['Eid']
df1['sal']

df1['Dname']

0         Dev
1       sales
2    accounts
3          HR
4     Testing
Name: Dname, dtype: object

In [ ]:
#to access a particular value
# df['colname'][index]

df1['Ename'][1]
df1['Ename'][3]
df1['Ename'][4]


df1['Dname'][1]
df1['Dname'][4]
df1['Dname'][3]


df1[::2]

df1[1::2]

  Ename  Eid    sal  deptno  Dname
1     B    2  30000      20  sales
3     D    4  15000      40     HR

In [ ]:
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  25000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
#modification
# syntax:
# df['colname'][index]=new value

# df1['Ename'][0]='Alex'
# df1['Ename'][1]='Bob'
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  25000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
df1['sal'][0]=50000
df1

<ipython-input-43-349bc9fc887e>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['sal'][0]=50000
<ipython-input-43-349bc9fc887e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['sal'][0]=50000

  Ename  Eid    sal  deptno     Dname
0     A    1  50000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
# df1['Ename'][4]='Edith'
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  50000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
# df1['Ename']='Alex'
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  50000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
df1

  Ename  Eid    sal  deptno     Dname
0     A    1  50000      10       Dev
1     B    2  30000      20     sales
2     C    3  50000      30  accounts
3     D    4  15000      40        HR
4     E    5   5000      50   Testing

In [ ]:
#Reading the files
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv',encoding='ISO-8859-1')
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv',encoding='ISO-8859-1')
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
# df=pd.read_csv('amazon_fires.csv',encoding='ISO-8859-1')
# df

In [ ]:
# df=pd.read_excel('amazon_fires.xlsx')
# df

In [ ]:
# pd.read_table('amazon.txt',encoding='ISO-8859-1')

In [ ]:
df1['B_group']=['o+','AB-','B+','O-','AB+']
df1

  Ename  Eid    sal  deptno     Dname B_group
0     A    1  50000      10       Dev      o+
1     B    2  30000      20     sales     AB-
2     C    3  50000      30  accounts      B+
3     D    4  15000      40        HR      O-
4     E    5   5000      50   Testing     AB+

In [ ]:
df1['Age']=[35,40,25,20,30]
df1

  Ename  Eid    sal  deptno     Dname B_group  Age
0     A    1  50000      10       Dev      o+   35
1     B    2  30000      20     sales     AB-   40
2     C    3  50000      30  accounts      B+   25
3     D    4  15000      40        HR      O-   20
4     E    5   5000      50   Testing     AB+   30

In [ ]:
df1['Contact']=[7889908978,6789907890,9089789988,7899887766,9112349089]

df1

  Ename  Eid    sal  deptno     Dname B_group  Age     Contact
0     A    1  50000      10       Dev      o+   35  7889908978
1     B    2  30000      20     sales     AB-   40  6789907890
2     C    3  50000      30  accounts      B+   25  9089789988
3     D    4  15000      40        HR      O-   20  7899887766
4     E    5   5000      50   Testing     AB+   30  9112349089

In [ ]:
df['num']=np.arange(1,6455)
df

       ano       mes     estado   numero  encontro   num
0     1998   Janeiro       Acre  0 Fires  1/1/1998     1
1     1999   Janeiro       Acre  0 Fires  1/1/1999     2
2     2000   Janeiro       Acre  0 Fires  1/1/2000     3
3     2001   Janeiro       Acre  0 Fires  1/1/2001     4
4     2002   Janeiro       Acre  0 Fires  1/1/2002     5
...    ...       ...        ...      ...       ...   ...
6449  2012  Dezembro  Tocantins      128  1/1/2012  6450
6450  2013  Dezembro  Tocantins       85  1/1/2013  6451
6451  2014  Dezembro  Tocantins      223  1/1/2014  6452
6452  2015  Dezembro  Tocantins      373  1/1/2015  6453
6453  2016  Dezembro  Tocantins      119  1/1/2016  6454

[6454 rows x 6 columns]

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/titanic.csv')
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
df.head()

df.head(50)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0
10,1,"Astor, Col. John Jacob",male,47.0000,1,0,PC 17757,227.5250,C62 C64,C,0
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0000,1,0,PC 17757,227.5250,C62 C64,C,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0000,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0000,0,0,19877,78.8500,NaN,S,1
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
16,1,"Baxter, Mr. Quigg Edmond",male,24.0000,0,1,PC 17558,247.5208,B58 B60,C,0
17,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0000,0,1,PC 17558,247.5208,B58 B60,C,1
18,1,"Bazzani, Miss. Albina",female,32.0000,0,0,11813,76.2917,D15,C,1
19,1,"Beattie, Mr. Thomson",male,36.0000,0,0,13050,75.2417,C6,C,0
20,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,52.5542,D35,S,1
21,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0000,1,1,11751,52.5542,D35,S,1
22,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,30.0000,C148,C,1
23,1,"Bidois, Miss. Rosalie",female,42.0000,0,0,PC 17757,227.5250,NaN,C,1
24,1,"Bird, Miss. Ellen",female,29.0000,0,0,PC 17483,221.7792,C97,S,1
25,1,"Birnbaum, Mr. Jakob",male,25.0000,0,0,13905,26.0000,NaN,C,0
26,1,"Bishop, Mr. Dickinson H",male,25.0000,1,0,11967,91.0792,B49,C,1
27,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0000,1,0,11967,91.0792,B49,C,1
28,1,"Bissette, Miss. Amelia",female,35.0000,0,0,PC 17760,135.6333,C99,S,1
29,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0000,0,0,110564,26.5500,C52,S,1
30,1,"Blackwell, Mr. Stephen Weart",male,45.0000,0,0,113784,35.5000,T,S,0
31,1,"Blank, Mr. Henry",male,40.0000,0,0,112277,31.0000,A31,C,1
32,1,"Bonnell, Miss. Caroline",female,30.0000,0,0,36928,164.8667,C7,S,1
33,1,"Bonnell, Miss. Elizabeth",female,58.0000,0,0,113783,26.5500,C103,S,1
34,1,"Borebank, Mr. John James",male,42.0000,0,0,110489,26.5500,D22,S,0
35,1,"Bowen, Miss. Grace Scott",female,45.0000,0,0,PC 17608,262.3750,NaN,C,1
36,1,"Bowerman, Miss. Elsie Edith",female,22.0000,0,1,113505,55.0000,E33,S,1
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
38,1,"Brady, Mr. John Bertram",male,41.0000,0,0,113054,30.5000,A21,S,0
39,1,"Brandeis, Mr. Emil",male,48.0000,0,0,PC 17591,50.4958,B10,C,0
40,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,0
41,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0000,0,0,PC 17610,27.7208,B4,C,1
42,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0000,2,0,11769,51.4792,C101,S,1
43,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0000,0,0,11813,76.2917,D15,C,1
44,1,"Burns, Miss. Elizabeth Margaret",female,41.0000,0,0,16966,134.5000,E40,C,1
45,1,"Butt, Major. Archibald Willingham",male,45.0000,0,0,113050,26.5500,B38,S,0
46,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,0
47,1,"Calderhead, Mr. Edward Pennington",male,42.0000,0,0,PC 17476,26.2875,E24,S,1
48,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0000,0,0,PC 17606,27.4458,NaN,C,1
49,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0000,0,1,PC 17755,512.3292,B51 B53 B55,C,1

In [ ]:
df.tail()
df.tail(10)
df.tail(30)
df.tail(100)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1209,3,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9000,NaN,S,0
1210,3,"Skoog, Mr. Wilhelm",male,40.0,1,4,347088,27.9000,NaN,S,0
1211,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S,0
1212,3,"Slabenoff, Mr. Petco",male,NaN,0,0,349214,7.8958,NaN,S,0
1213,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [ ]:
df1=pd.read_csv('https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv',encoding='ISO-8859-1')
df1

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [ ]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
df.describe()

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [ ]:
df.describe(include=object)

                        name   sex    ticket        cabin embarked
count                   1309  1309      1309          295     1307
unique                  1307     2       929          186        3
top     Connolly, Miss. Kate  male  CA. 2343  C23 C25 C27        S
freq                       2   843        11            6      914

In [ ]:
df.shape
df1.shape

(6454, 5)

In [ ]:
df.columns
df1.columns

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='object')

In [ ]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
df['sex'].unique()
df['pclass'].unique()
df['survived'].unique()
df['cabin'].unique()
df['embarked'].unique()

array(['S', 'C', nan, 'Q'], dtype=object)

In [ ]:
df['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [ ]:
df['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [ ]:
df['embarked'].value_counts()

embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [ ]:
df['cabin'].value_counts()

cabin
C23 C25 C27        6
G6                 5
B57 B59 B63 B66    5
F4                 4
F33                4
                  ..
C132               1
E60                1
B52 B54 B56        1
C49                1
F38                1
Name: count, Length: 186, dtype: int64

In [ ]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
df['survived'].value_counts()

survived
0    809
1    500
Name: count, dtype: int64